// Code generated by swaggo/swag at 2023-06-12 15:00:09.249582 +0800 CST m=+1.863423084. DO NOT EDIT.

package doc

import "github.com/swaggo/swag"

const docTemplateRuleEngine = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json",
        "text/xml",
        "text/plain",
        "text/html",
        "application/x-www-form-urlencoded"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "zhangyongxiang",
            "email": "zhangyongxiang@baidu.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/soe/rule-engine/sources": {
            "get": {
                "description": "自定义Source列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "自定义Source列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_.SourceListElement"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/workspaces/{workspaceID}/projects/{projectName}/analyticsjobs": {
            "post": {
                "description": "普通函数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "function"
                ],
                "summary": "普通函数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspaceId",
                        "name": "workspaceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "projectName",
                        "name": "projectName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "_.SourceListElement": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoRuleEngine holds exported Swagger Info so clients can modify it
var SwaggerInfoRuleEngine = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "rule engine swagger api specification",
	Description:      "rule engine api document，restful api",
	InfoInstanceName: "RuleEngine",
	SwaggerTemplate:  docTemplateRuleEngine,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoRuleEngine.InstanceName(), SwaggerInfoRuleEngine)
}
