basePath: /
consumes:
- application/json
- text/xml
- text/plain
- text/html
- application/x-www-form-urlencoded
definitions:
  _.SourceListElement:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: zhangyongxiang@baidu.com
    name: zhangyongxiang
  description: rule engine api document，restful api
  title: rule engine swagger api specification
  version: "1.0"
paths:
  /soe/rule-engine/sources:
    get:
      consumes:
      - application/json
      description: 自定义Source列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/_.SourceListElement'
        "500":
          description: internal server error
          schema:
            type: string
      summary: 自定义Source列表
      tags:
      - source
  /v1/workspaces/{workspaceID}/projects/{projectName}/analyticsjobs:
    post:
      consumes:
      - application/json
      description: 普通函数
      parameters:
      - description: workspaceId
        in: path
        name: workspaceID
        required: true
        type: string
      - description: projectName
        in: path
        name: projectName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: 普通函数
      tags:
      - function
swagger: "2.0"
