basePath: /
consumes:
- application/json
- text/xml
- text/plain
- text/html
- application/x-www-form-urlencoded
info:
  contact:
    email: zhangyongxiang@baidu.com
    name: zhangyongxiang
  description: rule engine api document，restful api
  title: rule engine swagger api specification
  version: "1.0"
paths:
  /v1/workspaces/{workspaceID}/projects/{projectName}/analyticsjobs:
    post:
      consumes:
      - application/json
      description: 创建流/批分析JOB
      parameters:
      - description: workspaceId
        in: path
        name: workspaceID
        required: true
        type: string
      - description: projectName
        in: path
        name: projectName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: 创建流/批分析JOB
      tags:
      - analytic
swagger: "2.0"
