// Code generated by swaggo/swag at 2023-06-07 17:02:47.642888 +0800 CST m=+0.192665293. DO NOT EDIT.

package doc

import "github.com/swaggo/swag"

const docTemplateRuleEngine = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json",
        "text/xml",
        "text/plain",
        "text/html",
        "application/x-www-form-urlencoded"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "zhangyongxiang",
            "email": "zhangyongxiang@baidu.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/workspaces/{workspaceID}/projects/{projectName}/analyticsjobs": {
            "post": {
                "description": "创建流/批分析JOB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytic"
                ],
                "summary": "创建流/批分析JOB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspaceId",
                        "name": "workspaceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "projectName",
                        "name": "projectName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfoRuleEngine holds exported Swagger Info so clients can modify it
var SwaggerInfoRuleEngine = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "rule engine swagger api specification",
	Description:      "rule engine api document，restful api",
	InfoInstanceName: "RuleEngine",
	SwaggerTemplate:  docTemplateRuleEngine,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoRuleEngine.InstanceName(), SwaggerInfoRuleEngine)
}
