# app.toml: 应用主配置文件
AppName = "RuleEngine"
RunMode = "debug" # debug/test/release

[HTTPServer]
# 监听地址，必填
Listen = "0.0.0.0:8080"
# 读超时时间（单位ms），选填，默认20s
ReadTimeout = 60000
# 写超时时间（单位ms），选填，默认10s
WriteTimeout = 40000
# Idle超时时间（单位ms），选填，默认10s
IdleTimeout = 10000 # 10s
# 最大header空间，选填，默认100k
MaxHeaderBytes = 100 # 100k
# 对外接口通用前缀，配置后所有接口path将默认加上该前缀，选填，默认为空
APIBasePath = ""

[DB]
Driver = "MySQL" # 支持MySQL, SQLite, PostgreSQL, ClickHouse, 选填，默认为MySQL
Host = "10.162.195.168"
Port = 8270
User = "root"
Password = "bigdataNV7U"
DB = "soe_engine"
#可拓展的dsn params 可参考 https://github.com/go-sql-driver/mysql/blob/master/dsn.go
DSNParams = "collation=utf8mb4_unicode_ci&parseTime=true&loc=Local&parseTime=True"
ConnMaxIdleTime = 100
ConnMaxLifeTime = 100
MaxIdleConns = 10
MaxOpenConns = 10

